### ISSUE TITLE
Bot unresponsive to anything but !help

### ISSUE THREAD

**Issue by DiabloStorm** [LaBaleineFr/ImageBaleine#11]
Typing !help works, but then copy pasting even the supplied example commands does absolutely nothing

i.e. "!c cute gif" does nothing

!s commands also do nothing.

The bot does nothing.

**Comment by Pouleyy** [comment]
Hello ! 

You’re hosting your own or using Okedan ? 

If you’re using Okedan, I’ve restart it. There was a problem. It works now. Is that ok for you ?

I will have to remade the whole bot when I’ll have time to be less error prone

**Comment by DiabloStorm** [comment]
The problem is resolved, thank you.
